package com.practice.dianping.dal;

import com.practice.dianping.model.ShopModel;

import java.util.List;

public interface ShopModelMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table shop
   *
   * @mbg.generated Mon Apr 06 17:14:09 CST 2020
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table shop
   *
   * @mbg.generated Mon Apr 06 17:14:09 CST 2020
   */
  int insert(ShopModel record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table shop
   *
   * @mbg.generated Mon Apr 06 17:14:09 CST 2020
   */
  int insertSelective(ShopModel record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table shop
   *
   * @mbg.generated Mon Apr 06 17:14:09 CST 2020
   */
  ShopModel selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table shop
   *
   * @mbg.generated Mon Apr 06 17:14:09 CST 2020
   */
  int updateByPrimaryKeySelective(ShopModel record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table shop
   *
   * @mbg.generated Mon Apr 06 17:14:09 CST 2020
   */
  int updateByPrimaryKey(ShopModel record);

  Integer countAllShop();

  List<ShopModel> selectAll();


}
